// Pre-loaded meal vault + default weekly plan + batch cook tasks
// -----------------------------------------------------------------------------
// Cal ranges are sensible defaults; user can edit in the vault.

const DEFAULT_MEALS = [
  // --- NIGERIAN SOUPS (dinners) ---
  { id: "efo-riro", name: "Efo riro", category: "soup", cuisine: "nigerian",
    caloriesAdult: 380, caloriesKid: 420, proteinType: "beef",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","anti-inflammatory"], prepTime: 60,
    notes: "Leafy green Nigerian stew — measured palm oil for adults." },
  { id: "okra-oil-free", name: "Okra soup (oil-free)", category: "soup", cuisine: "nigerian",
    caloriesAdult: 300, caloriesKid: 350, proteinType: "fish",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","prediabetes","anti-inflammatory"], prepTime: 45,
    notes: "No added oil — great for Stephen." },
  { id: "pepper-soup-chicken", name: "Pepper soup (chicken)", category: "soup", cuisine: "nigerian",
    caloriesAdult: 340, caloriesKid: 380, proteinType: "chicken",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["anti-inflammatory"], prepTime: 50,
    notes: "Mild spice version for kids." },
  { id: "pepper-soup-goat", name: "Pepper soup (goat meat)", category: "soup", cuisine: "nigerian",
    caloriesAdult: 420, caloriesKid: 460, proteinType: "goat",
    kidsFriendly: false, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 75,
    notes: "Richer red meat — rotate occasionally." },
  { id: "egusi", name: "Egusi soup", category: "soup", cuisine: "nigerian",
    caloriesAdult: 520, caloriesKid: 560, proteinType: "beef",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 70,
    notes: "Melon-seed soup — calorie dense, good for kids." },
  { id: "bitterleaf", name: "Bitterleaf soup", category: "soup", cuisine: "nigerian",
    caloriesAdult: 400, caloriesKid: 430, proteinType: "beef",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","anti-inflammatory"], prepTime: 65,
    notes: "" },
  { id: "catfish-pepper-soup", name: "Catfish pepper soup", category: "soup", cuisine: "nigerian",
    caloriesAdult: 310, caloriesKid: 350, proteinType: "fish",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","anti-inflammatory","prediabetes"], prepTime: 45,
    notes: "Lean, omega-rich. Kids portion deboned." },

  // --- RICE / GRAINS ---
  { id: "jollof-rice", name: "Jollof rice", category: "rice", cuisine: "nigerian",
    caloriesAdult: 480, caloriesKid: 520, proteinType: "chicken",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 50,
    notes: "Popular — controlled portion for adults." },
  { id: "fried-rice", name: "Fried rice", category: "rice", cuisine: "nigerian",
    caloriesAdult: 500, caloriesKid: 540, proteinType: "chicken",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 45,
    notes: "" },
  { id: "rice-beans", name: "White rice + beans", category: "rice", cuisine: "nigerian",
    caloriesAdult: 450, caloriesKid: 550, proteinType: "bean",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["prediabetes","blood-pressure"], prepTime: 40,
    notes: "Fibre + plant protein — good for Stephen." },
  { id: "coconut-rice", name: "Coconut rice", category: "rice", cuisine: "nigerian",
    caloriesAdult: 490, caloriesKid: 530, proteinType: "chicken",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 45, notes: "" },
  { id: "minced-spaghetti-ww", name: "Minced meat spaghetti (whole wheat)", category: "rice", cuisine: "western",
    caloriesAdult: 520, caloriesKid: 580, proteinType: "beef",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["prediabetes"], prepTime: 35,
    notes: "Whole-wheat pasta — slower glucose response." },
  { id: "cauli-rice-stew", name: "Cauliflower rice + Nigerian stew", category: "rice", cuisine: "mixed",
    caloriesAdult: 340, caloriesKid: 400, proteinType: "chicken",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["prediabetes","blood-pressure"], prepTime: 35,
    notes: "Low-carb swap for rice — Temi/Stephen friendly." },
  { id: "rice-salmon-bowl", name: "Rice & salmon bowl", category: "rice", cuisine: "mixed",
    caloriesAdult: 520, caloriesKid: 560, proteinType: "fish",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","anti-inflammatory"], prepTime: 30,
    notes: "Omega-3 rich." },

  // --- SWALLOWS (carbs served with soups) ---
  { id: "semovita", name: "Semovita", category: "swallow", cuisine: "nigerian",
    caloriesAdult: 280, caloriesKid: 320, proteinType: "none",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 10, notes: "" },
  { id: "pounded-yam", name: "Pounded yam", category: "swallow", cuisine: "nigerian",
    caloriesAdult: 320, caloriesKid: 360, proteinType: "none",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 15, notes: "" },
  { id: "eba", name: "Eba / garri", category: "swallow", cuisine: "nigerian",
    caloriesAdult: 300, caloriesKid: 340, proteinType: "none",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 8, notes: "" },
  { id: "amala", name: "Amala", category: "swallow", cuisine: "nigerian",
    caloriesAdult: 290, caloriesKid: 330, proteinType: "none",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["prediabetes"], prepTime: 10,
    notes: "Yam flour — lower GI than semo." },
  { id: "fufu", name: "Fufu", category: "swallow", cuisine: "nigerian",
    caloriesAdult: 300, caloriesKid: 340, proteinType: "none",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 12, notes: "" },
  { id: "rice-side", name: "White rice (side)", category: "swallow", cuisine: "mixed",
    caloriesAdult: 240, caloriesKid: 280, proteinType: "none",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 20, notes: "Paired as carb with soup." },
  { id: "yam-boiled", name: "Boiled yam (side)", category: "swallow", cuisine: "nigerian",
    caloriesAdult: 260, caloriesKid: 300, proteinType: "none",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["prediabetes"], prepTime: 20, notes: "" },

  // --- PROTEINS (mains/sides) ---
  { id: "grilled-chicken", name: "Grilled chicken", category: "protein", cuisine: "mixed",
    caloriesAdult: 280, caloriesKid: 320, proteinType: "chicken",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","prediabetes"], prepTime: 25, notes: "" },
  { id: "grilled-tilapia", name: "Grilled tilapia", category: "protein", cuisine: "mixed",
    caloriesAdult: 240, caloriesKid: 280, proteinType: "fish",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","anti-inflammatory","prediabetes"], prepTime: 25, notes: "" },
  { id: "grilled-catfish", name: "Grilled catfish", category: "protein", cuisine: "nigerian",
    caloriesAdult: 300, caloriesKid: 340, proteinType: "fish",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","anti-inflammatory"], prepTime: 30, notes: "" },
  { id: "stir-shrimp", name: "Stir-fried shrimp", category: "protein", cuisine: "mixed",
    caloriesAdult: 260, caloriesKid: 300, proteinType: "shrimp",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["prediabetes"], prepTime: 20, notes: "" },
  { id: "lean-mince", name: "Lean minced beef", category: "protein", cuisine: "mixed",
    caloriesAdult: 290, caloriesKid: 340, proteinType: "beef",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 20, notes: "" },
  { id: "deli-turkey", name: "Deli turkey", category: "protein", cuisine: "western",
    caloriesAdult: 150, caloriesKid: 180, proteinType: "turkey",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure"], prepTime: 2,
    notes: "Low-sodium variety preferred for Stephen." },
  { id: "boiled-eggs", name: "Boiled eggs", category: "protein", cuisine: "mixed",
    caloriesAdult: 140, caloriesKid: 160, proteinType: "egg",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["prediabetes"], prepTime: 12, notes: "" },
  { id: "canned-tuna", name: "Canned tuna", category: "protein", cuisine: "western",
    caloriesAdult: 160, caloriesKid: 180, proteinType: "fish",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","anti-inflammatory"], prepTime: 1, notes: "" },
  { id: "moi-moi", name: "Moi moi", category: "protein", cuisine: "nigerian",
    caloriesAdult: 250, caloriesKid: 300, proteinType: "bean",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","prediabetes"], prepTime: 70,
    notes: "Steamed bean pudding." },

  // --- ADULT BREAKFASTS (rotating A/B) ---
  { id: "eggs-toast-avo", name: "Scrambled eggs + toast + avocado", category: "breakfast-adult", cuisine: "mixed",
    caloriesAdult: 420, caloriesKid: 460, proteinType: "egg",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","anti-inflammatory"], prepTime: 10, notes: "" },
  { id: "oatmeal-almond-apple", name: "Oatmeal + almond milk + apple", category: "breakfast-adult", cuisine: "western",
    caloriesAdult: 340, caloriesKid: 400, proteinType: "none",
    kidsFriendly: true, nutAlert: true, stephenFriendly: true,
    stephenBenefits: ["prediabetes","blood-pressure"], prepTime: 10,
    notes: "Contains almond (tree nut) — NOT for school lunch." },
  { id: "green-smoothie", name: "Green smoothie (spinach + apple + cucumber + lemon)", category: "breakfast-adult", cuisine: "western",
    caloriesAdult: 180, caloriesKid: 220, proteinType: "none",
    kidsFriendly: false, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","anti-inflammatory","prediabetes"], prepTime: 5, notes: "" },
  { id: "french-toast-light", name: "French toast (light)", category: "breakfast-adult", cuisine: "western",
    caloriesAdult: 380, caloriesKid: 450, proteinType: "egg",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 15, notes: "" },
  { id: "yam-egg-sauce", name: "Boiled yam + egg sauce", category: "breakfast-adult", cuisine: "nigerian",
    caloriesAdult: 460, caloriesKid: 520, proteinType: "egg",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 25, notes: "" },
  { id: "nigerian-fry-up", name: "Full Nigerian fry-up", category: "breakfast-adult", cuisine: "nigerian",
    caloriesAdult: 620, caloriesKid: 700, proteinType: "mixed",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 30, notes: "Indulgent — weekends only." },
  { id: "egg-turkey-wrap", name: "Egg & turkey wrap", category: "breakfast-adult", cuisine: "western",
    caloriesAdult: 380, caloriesKid: 440, proteinType: "turkey",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure"], prepTime: 10, notes: "" },

  // --- KID BREAKFASTS (calorie-dense) ---
  { id: "oatmeal-milk-pb", name: "Oatmeal + whole milk + banana + peanut butter", category: "breakfast-kid", cuisine: "western",
    caloriesAdult: 480, caloriesKid: 560, proteinType: "none",
    kidsFriendly: true, nutAlert: true, stephenFriendly: false,
    stephenBenefits: [], prepTime: 10,
    notes: "Home breakfast only — contains peanut." },
  { id: "weight-gain-smoothie", name: "Weight-gain smoothie (banana + mango + milk + peanut butter)", category: "breakfast-kid", cuisine: "western",
    caloriesAdult: 400, caloriesKid: 520, proteinType: "none",
    kidsFriendly: true, nutAlert: true, stephenFriendly: false,
    stephenBenefits: [], prepTime: 5,
    notes: "Home breakfast only — contains peanut." },
  { id: "pancakes-pb", name: "Pancakes + banana + peanut butter", category: "breakfast-kid", cuisine: "western",
    caloriesAdult: 520, caloriesKid: 600, proteinType: "none",
    kidsFriendly: true, nutAlert: true, stephenFriendly: false,
    stephenBenefits: [], prepTime: 20,
    notes: "Home breakfast only — contains peanut." },
  { id: "french-toast-honey-berries", name: "French toast + honey + strawberries", category: "breakfast-kid", cuisine: "western",
    caloriesAdult: 440, caloriesKid: 520, proteinType: "egg",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 15, notes: "" },
  { id: "cereal-milk-egg", name: "Cereal + whole milk + boiled egg", category: "breakfast-kid", cuisine: "western",
    caloriesAdult: 380, caloriesKid: 460, proteinType: "egg",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 8, notes: "" },

  // --- KIDS SCHOOL LUNCHES (12-option rotation) ---
  { id: "sl-jollof-chicken", name: "Jollof rice + chicken (thermos)", category: "kids-lunch", cuisine: "nigerian",
    caloriesAdult: 520, caloriesKid: 560, proteinType: "chicken",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 5, notes: "Reheat from batch." },
  { id: "sl-moi-moi-egg", name: "Moi moi + boiled egg (thermos)", category: "kids-lunch", cuisine: "nigerian",
    caloriesAdult: 380, caloriesKid: 460, proteinType: "bean",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["prediabetes","blood-pressure"], prepTime: 5, notes: "" },
  { id: "sl-tuna-sandwich", name: "Tuna sandwich", category: "kids-lunch", cuisine: "western",
    caloriesAdult: 360, caloriesKid: 440, proteinType: "fish",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["anti-inflammatory"], prepTime: 5, notes: "" },
  { id: "sl-chicken-wrap", name: "Chicken wrap", category: "kids-lunch", cuisine: "western",
    caloriesAdult: 400, caloriesKid: 480, proteinType: "chicken",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: [], prepTime: 8, notes: "" },
  { id: "sl-pasta-tuna-salad", name: "Pasta salad + tuna", category: "kids-lunch", cuisine: "western",
    caloriesAdult: 420, caloriesKid: 500, proteinType: "fish",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["anti-inflammatory"], prepTime: 10, notes: "" },
  { id: "sl-egg-cheese-wrap", name: "Egg & cheese wrap", category: "kids-lunch", cuisine: "western",
    caloriesAdult: 420, caloriesKid: 500, proteinType: "egg",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 8, notes: "" },
  { id: "sl-cheese-chicken-sandwich", name: "Cheese & chicken sandwich", category: "kids-lunch", cuisine: "western",
    caloriesAdult: 440, caloriesKid: 520, proteinType: "chicken",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 5, notes: "" },
  { id: "sl-pasta-chicken-sauce", name: "Pasta + tomato chicken sauce (thermos)", category: "kids-lunch", cuisine: "mixed",
    caloriesAdult: 460, caloriesKid: 540, proteinType: "chicken",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: [], prepTime: 5, notes: "Reheat from batch." },
  { id: "sl-chicken-rice", name: "Chicken rice (thermos)", category: "kids-lunch", cuisine: "mixed",
    caloriesAdult: 480, caloriesKid: 560, proteinType: "chicken",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 5, notes: "" },
  { id: "sl-beans-plantain", name: "Beans + plantain (thermos)", category: "kids-lunch", cuisine: "nigerian",
    caloriesAdult: 440, caloriesKid: 540, proteinType: "bean",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","prediabetes"], prepTime: 5, notes: "" },
  { id: "sl-mini-pizza", name: "Mini pizza slices", category: "kids-lunch", cuisine: "western",
    caloriesAdult: 400, caloriesKid: 480, proteinType: "mixed",
    kidsFriendly: true, nutAlert: false, stephenFriendly: false,
    stephenBenefits: [], prepTime: 12, notes: "" },
  { id: "sl-rice-cake-cheese", name: "Rice cake + cheese", category: "kids-lunch", cuisine: "western",
    caloriesAdult: 300, caloriesKid: 380, proteinType: "none",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: [], prepTime: 3, notes: "Light — pair with fruit." },

  // --- ADULT LUNCHES (weekday light / weekend family) ---
  { id: "adult-salad-chicken", name: "Big salad + grilled chicken", category: "lunch-adult", cuisine: "western",
    caloriesAdult: 420, caloriesKid: 480, proteinType: "chicken",
    kidsFriendly: false, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","prediabetes","anti-inflammatory"], prepTime: 10, notes: "" },
  { id: "adult-tuna-bowl", name: "Tuna + greens bowl", category: "lunch-adult", cuisine: "western",
    caloriesAdult: 400, caloriesKid: 440, proteinType: "fish",
    kidsFriendly: false, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure","anti-inflammatory"], prepTime: 8, notes: "" },
  { id: "adult-leftover-soup", name: "Leftover soup (lunch portion)", category: "lunch-adult", cuisine: "nigerian",
    caloriesAdult: 380, caloriesKid: 440, proteinType: "mixed",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: [], prepTime: 5, notes: "Uses Sunday batch — controlled portion." },
  { id: "adult-turkey-wrap", name: "Turkey wrap + veg", category: "lunch-adult", cuisine: "western",
    caloriesAdult: 420, caloriesKid: 480, proteinType: "turkey",
    kidsFriendly: true, nutAlert: false, stephenFriendly: true,
    stephenBenefits: ["blood-pressure"], prepTime: 8, notes: "" },
];

// Ingredient lists for the grocery generator.
// Grouped by section. Each meal maps to simple ingredient strings with a section.
const MEAL_INGREDIENTS = {
  "efo-riro": [
    ["Spinach (fresh)", "Vegetables"],
    ["Palm oil", "Pantry"],
    ["Scotch bonnet / Cameroon pepper", "Vegetables"],
    ["Beef (stew cut)", "Proteins"],
    ["Smoked fish", "Proteins"],
    ["Locust beans (iru)", "Pantry"],
    ["Stock cubes", "Pantry"],
    ["Onions", "Vegetables"],
  ],
  "okra-oil-free": [
    ["Fresh okra", "Vegetables"],
    ["Catfish", "Proteins"],
    ["Scotch bonnet", "Vegetables"],
    ["Crayfish (ground)", "Pantry"],
    ["Onions", "Vegetables"],
  ],
  "pepper-soup-chicken": [
    ["Chicken (whole, cut)", "Proteins"],
    ["Pepper soup spice mix", "Pantry"],
    ["Scent leaves", "Vegetables"],
    ["Ginger", "Vegetables"],
    ["Garlic", "Vegetables"],
  ],
  "pepper-soup-goat": [
    ["Goat meat", "Proteins"],
    ["Pepper soup spice mix", "Pantry"],
    ["Scent leaves", "Vegetables"],
  ],
  "egusi": [
    ["Egusi (ground melon seed)", "Pantry"],
    ["Beef (stew cut)", "Proteins"],
    ["Smoked fish", "Proteins"],
    ["Bitter leaf or ugu", "Vegetables"],
    ["Palm oil", "Pantry"],
    ["Stock cubes", "Pantry"],
  ],
  "bitterleaf": [
    ["Bitter leaf (washed)", "Vegetables"],
    ["Cocoyam paste", "Pantry"],
    ["Beef (stew cut)", "Proteins"],
    ["Stockfish", "Proteins"],
    ["Palm oil", "Pantry"],
  ],
  "catfish-pepper-soup": [
    ["Catfish (cleaned, cut)", "Proteins"],
    ["Pepper soup spice", "Pantry"],
    ["Scent leaves", "Vegetables"],
    ["Ginger", "Vegetables"],
  ],
  "jollof-rice": [
    ["Long grain rice", "Carbs & Staples"],
    ["Roma tomatoes", "Vegetables"],
    ["Red bell pepper", "Vegetables"],
    ["Chicken", "Proteins"],
    ["Vegetable oil", "Pantry"],
    ["Tomato paste", "Pantry"],
    ["Onions", "Vegetables"],
  ],
  "fried-rice": [
    ["Long grain rice", "Carbs & Staples"],
    ["Mixed veg (carrot, peas, sweet corn)", "Vegetables"],
    ["Liver (optional)", "Proteins"],
    ["Chicken", "Proteins"],
    ["Curry powder", "Pantry"],
  ],
  "rice-beans": [
    ["Long grain rice", "Carbs & Staples"],
    ["Honey beans / brown beans", "Carbs & Staples"],
    ["Onions", "Vegetables"],
    ["Palm oil", "Pantry"],
  ],
  "coconut-rice": [
    ["Long grain rice", "Carbs & Staples"],
    ["Coconut milk", "Pantry"],
    ["Mixed veg", "Vegetables"],
    ["Chicken", "Proteins"],
  ],
  "minced-spaghetti-ww": [
    ["Whole wheat spaghetti", "Carbs & Staples"],
    ["Lean minced beef", "Proteins"],
    ["Roma tomatoes", "Vegetables"],
    ["Tomato paste", "Pantry"],
    ["Garlic", "Vegetables"],
    ["Oregano", "Pantry"],
  ],
  "cauli-rice-stew": [
    ["Cauliflower (fresh or frozen riced)", "Vegetables"],
    ["Roma tomatoes", "Vegetables"],
    ["Chicken", "Proteins"],
    ["Red bell pepper", "Vegetables"],
  ],
  "rice-salmon-bowl": [
    ["Salmon fillets", "Proteins"],
    ["Brown rice", "Carbs & Staples"],
    ["Broccoli", "Vegetables"],
    ["Soy sauce (low-sodium)", "Pantry"],
  ],
  "semovita": [["Semovita flour", "Carbs & Staples"]],
  "pounded-yam": [["Pounded yam flour / fresh yam", "Carbs & Staples"]],
  "eba": [["Garri (fine)", "Carbs & Staples"]],
  "amala": [["Yam flour (elubo)", "Carbs & Staples"]],
  "fufu": [["Fufu flour", "Carbs & Staples"]],
  "rice-side": [["Long grain rice", "Carbs & Staples"]],
  "yam-boiled": [["Fresh white yam", "Carbs & Staples"]],
  "grilled-chicken": [
    ["Chicken breast", "Proteins"],
    ["Lemon", "Fruits"],
    ["Mixed herbs", "Pantry"],
  ],
  "grilled-tilapia": [["Tilapia fillets", "Proteins"], ["Lemon", "Fruits"]],
  "grilled-catfish": [["Catfish (whole)", "Proteins"], ["Yaji / suya spice", "Pantry"]],
  "stir-shrimp": [["Shrimp (frozen)", "Proteins"], ["Bell peppers", "Vegetables"], ["Garlic", "Vegetables"]],
  "lean-mince": [["Lean minced beef", "Proteins"]],
  "deli-turkey": [["Deli turkey (low-sodium)", "Proteins"]],
  "boiled-eggs": [["Eggs (dozen)", "Proteins"]],
  "canned-tuna": [["Canned tuna", "Proteins"]],
  "moi-moi": [
    ["Honey beans (peeled)", "Carbs & Staples"],
    ["Red bell pepper", "Vegetables"],
    ["Eggs", "Proteins"],
    ["Crayfish", "Pantry"],
    ["Palm oil", "Pantry"],
  ],

  // Breakfasts (adult)
  "eggs-toast-avo": [["Eggs", "Proteins"], ["Whole-grain bread", "Carbs & Staples"], ["Avocado", "Fruits"]],
  "oatmeal-almond-apple": [["Rolled oats", "Carbs & Staples"], ["Almond milk", "Dairy"], ["Apples", "Fruits"]],
  "green-smoothie": [["Baby spinach", "Vegetables"], ["Apples", "Fruits"], ["Cucumber", "Vegetables"], ["Lemon", "Fruits"]],
  "french-toast-light": [["Whole-grain bread", "Carbs & Staples"], ["Eggs", "Proteins"], ["Milk", "Dairy"], ["Cinnamon", "Pantry"]],
  "yam-egg-sauce": [["Fresh white yam", "Carbs & Staples"], ["Eggs", "Proteins"], ["Roma tomatoes", "Vegetables"], ["Onions", "Vegetables"]],
  "nigerian-fry-up": [["Plantain", "Fruits"], ["Eggs", "Proteins"], ["Sausage", "Proteins"], ["Beans", "Carbs & Staples"]],
  "egg-turkey-wrap": [["Tortillas (whole wheat)", "Carbs & Staples"], ["Eggs", "Proteins"], ["Deli turkey", "Proteins"], ["Cheese slices", "Dairy"]],

  // Breakfasts (kids)
  "oatmeal-milk-pb": [["Rolled oats", "Carbs & Staples"], ["Whole milk", "Dairy"], ["Bananas", "Fruits"], ["Peanut butter", "Pantry"]],
  "weight-gain-smoothie": [["Bananas", "Fruits"], ["Mango (frozen)", "Fruits"], ["Whole milk", "Dairy"], ["Peanut butter", "Pantry"]],
  "pancakes-pb": [["Pancake mix", "Carbs & Staples"], ["Bananas", "Fruits"], ["Peanut butter", "Pantry"], ["Whole milk", "Dairy"]],
  "french-toast-honey-berries": [["Whole-grain bread", "Carbs & Staples"], ["Eggs", "Proteins"], ["Honey", "Pantry"], ["Strawberries", "Fruits"]],
  "cereal-milk-egg": [["Kids cereal", "Carbs & Staples"], ["Whole milk", "Dairy"], ["Eggs", "Proteins"]],

  // Kids school lunches (most reuse weekend cooking)
  "sl-jollof-chicken": [],
  "sl-moi-moi-egg": [["Eggs", "Proteins"]],
  "sl-tuna-sandwich": [["Sandwich bread", "Carbs & Staples"], ["Canned tuna", "Proteins"], ["Mayo", "Pantry"], ["Lettuce", "Vegetables"]],
  "sl-chicken-wrap": [["Tortilla wraps", "Carbs & Staples"], ["Cooked chicken", "Proteins"], ["Lettuce", "Vegetables"], ["Cheese slices", "Dairy"]],
  "sl-pasta-tuna-salad": [["Pasta (any short shape)", "Carbs & Staples"], ["Canned tuna", "Proteins"], ["Sweet corn", "Vegetables"], ["Mayo", "Pantry"]],
  "sl-egg-cheese-wrap": [["Tortilla wraps", "Carbs & Staples"], ["Eggs", "Proteins"], ["Cheese slices", "Dairy"]],
  "sl-cheese-chicken-sandwich": [["Sandwich bread", "Carbs & Staples"], ["Cooked chicken", "Proteins"], ["Cheese slices", "Dairy"]],
  "sl-pasta-chicken-sauce": [["Pasta", "Carbs & Staples"], ["Cooked chicken", "Proteins"], ["Tomato sauce", "Pantry"]],
  "sl-chicken-rice": [["Long grain rice", "Carbs & Staples"], ["Cooked chicken", "Proteins"]],
  "sl-beans-plantain": [["Honey beans", "Carbs & Staples"], ["Plantain (ripe)", "Fruits"]],
  "sl-mini-pizza": [["Mini pizza bases", "Carbs & Staples"], ["Mozzarella", "Dairy"], ["Tomato sauce", "Pantry"], ["Pepperoni", "Proteins"]],
  "sl-rice-cake-cheese": [["Rice cakes", "Carbs & Staples"], ["Cheese slices", "Dairy"], ["Grapes or apples", "Fruits"]],

  // Adult lunches
  "adult-salad-chicken": [["Mixed salad greens", "Vegetables"], ["Cherry tomatoes", "Vegetables"], ["Cooked chicken", "Proteins"], ["Olive oil", "Pantry"]],
  "adult-tuna-bowl": [["Canned tuna", "Proteins"], ["Mixed greens", "Vegetables"], ["Cucumber", "Vegetables"]],
  "adult-leftover-soup": [],
  "adult-turkey-wrap": [["Tortilla wraps", "Carbs & Staples"], ["Deli turkey", "Proteins"], ["Lettuce", "Vegetables"], ["Cheese slices", "Dairy"]],
};

// -----------------------------------------------------------------------------
// Default week: Sunday → Saturday
// Soups are cooked Sunday and repeat once later in the week with a different carb.
// -----------------------------------------------------------------------------

const DEFAULT_PLAN = {
  Sun: {
    breakfast:    { type: "family",  adultMealId: "eggs-toast-avo",    kidMealId: "eggs-toast-avo" },
    lunch:        { type: "family",  adultMealId: "jollof-rice",       kidMealId: "jollof-rice" },
    dinner:       { type: "family",  adultMealId: "efo-riro",          adultSideId: "semovita",
                    kidMealId: "efo-riro",     kidSideId: "semovita",
                    soupKey: "efo-riro", freshCook: true },
  },
  Mon: {
    breakfast:    { type: "split",   adultMealId: "green-smoothie",    kidMealId: "oatmeal-milk-pb" },
    lunch:        { type: "split",   adultMealId: "adult-salad-chicken", kidMealId: "sl-jollof-chicken" },
    dinner:       { type: "family",  adultMealId: "egusi",             adultSideId: "pounded-yam",
                    kidMealId: "egusi",        kidSideId: "pounded-yam",
                    soupKey: "egusi", freshCook: true },
  },
  Tue: {
    breakfast:    { type: "split",   adultMealId: "oatmeal-almond-apple", kidMealId: "weight-gain-smoothie" },
    lunch:        { type: "split",   adultMealId: "adult-tuna-bowl",    kidMealId: "sl-moi-moi-egg" },
    dinner:       { type: "family",  adultMealId: "pepper-soup-chicken", adultSideId: "rice-side",
                    kidMealId: "pepper-soup-chicken", kidSideId: "rice-side",
                    soupKey: "pepper-soup-chicken", freshCook: true },
  },
  Wed: {
    breakfast:    { type: "split",   adultMealId: "green-smoothie",    kidMealId: "pancakes-pb" },
    lunch:        { type: "split",   adultMealId: "adult-leftover-soup", kidMealId: "sl-tuna-sandwich" },
    dinner:       { type: "family",  adultMealId: "efo-riro",          adultSideId: "rice-side",
                    kidMealId: "efo-riro",     kidSideId: "rice-side",
                    soupKey: "efo-riro", repeat: true },
  },
  Thu: {
    breakfast:    { type: "split",   adultMealId: "oatmeal-almond-apple", kidMealId: "french-toast-honey-berries" },
    lunch:        { type: "split",   adultMealId: "adult-turkey-wrap",  kidMealId: "sl-chicken-wrap" },
    dinner:       { type: "family",  adultMealId: "egusi",             adultSideId: "eba",
                    kidMealId: "egusi",        kidSideId: "eba",
                    soupKey: "egusi", repeat: true },
  },
  Fri: {
    breakfast:    { type: "split",   adultMealId: "egg-turkey-wrap",   kidMealId: "cereal-milk-egg" },
    lunch:        { type: "split",   adultMealId: "adult-salad-chicken", kidMealId: "sl-pasta-tuna-salad" },
    dinner:       { type: "family",  adultMealId: "pepper-soup-chicken", adultSideId: "yam-boiled",
                    kidMealId: "pepper-soup-chicken", kidSideId: "yam-boiled",
                    soupKey: "pepper-soup-chicken", repeat: true },
  },
  Sat: {
    breakfast:    { type: "family",  adultMealId: "yam-egg-sauce",     kidMealId: "yam-egg-sauce" },
    lunch:        { type: "family",  adultMealId: "rice-salmon-bowl",  kidMealId: "rice-salmon-bowl" },
    dinner:       { type: "family",  adultMealId: "grilled-catfish",   adultSideId: "amala",
                    kidMealId: "grilled-catfish", kidSideId: "amala",
                    flex: true },
  },
};

// -----------------------------------------------------------------------------
// Batch cook guide — Saturday tasks then Sunday tasks.
// -----------------------------------------------------------------------------
const BATCH_TASKS = [
  // Saturday
  { id: "sat-grocery",  day: "Saturday", title: "Grocery shop & unpack",
    minutes: 90, feeds: "Whole week",
    storage: "Veg in crisper; proteins: portion & freeze extras." },
  { id: "sat-wash-veg", day: "Saturday", title: "Wash & prep vegetables",
    minutes: 30, feeds: "All soups, salads, school lunches",
    storage: "Spinach dried & bagged; peppers blended & bagged." },
  { id: "sat-portion-proteins", day: "Saturday", title: "Portion proteins (beef, chicken, fish)",
    minutes: 25, feeds: "Sunday soups + weekday lunches",
    storage: "Zip bags, labelled, fridge/freezer." },
  { id: "sat-overnight-oats", day: "Saturday", title: "Prep overnight oats jars (for Tue/Thu)",
    minutes: 10, feeds: "Adult breakfasts Tue/Thu",
    storage: "Mason jars in fridge — up to 4 days." },
  { id: "sat-cook-salmon", day: "Saturday", title: "Cook Saturday dinner (grilled catfish + amala)",
    minutes: 50, feeds: "Saturday dinner",
    storage: "Eat fresh; leftovers → fridge." },

  // Sunday
  { id: "sun-soup1", day: "Sunday", title: "Cook Soup 1 — Efo riro (large pot)",
    minutes: 70, feeds: "Sun dinner + Wed dinner + Wed adult lunch",
    storage: "Half in fridge (use by Wed), half deep freeze if not using by Wed." },
  { id: "sun-soup2", day: "Sunday", title: "Cook Soup 2 — Egusi soup (large pot)",
    minutes: 75, feeds: "Mon dinner + Thu dinner",
    storage: "Half fridge, half freezer; label dates." },
  { id: "sun-soup3", day: "Sunday", title: "Cook Soup 3 — Pepper soup (chicken)",
    minutes: 55, feeds: "Tue dinner + Fri dinner",
    storage: "Half fridge, half freezer." },
  { id: "sun-moi-moi", day: "Sunday", title: "Steam moi moi batch",
    minutes: 75, feeds: "Tue school lunch + Sun lunch pairing",
    storage: "Cooled, wrapped, fridge up to 4 days." },
  { id: "sun-jollof", day: "Sunday", title: "Cook Jollof rice (Sun lunch + Mon school lunch)",
    minutes: 50, feeds: "Sun family lunch + Mon kids thermos",
    storage: "Portion Mon thermos serving separately." },
  { id: "sun-proteins-grill", day: "Sunday", title: "Grill chicken & shred (for wraps/sandwiches)",
    minutes: 30, feeds: "Mon/Wed/Fri adult lunches + Thu kids wrap + Cheese-chicken sandwich",
    storage: "Fridge in sealed container — use by Thursday." },
  { id: "sun-boil-eggs", day: "Sunday", title: "Boil 12 eggs",
    minutes: 15, feeds: "Breakfasts + Tue kids moi moi lunch",
    storage: "In shell, fridge up to 7 days." },
  { id: "sun-plantain", day: "Sunday", title: "Fry/boil plantain batch (for Fri beans&plantain)",
    minutes: 20, feeds: "Kids Fri lunch",
    storage: "Airtight fridge; reheat Fri morning." },
  { id: "sun-pack-snacks", day: "Sunday", title: "Pre-pack school snacks & fruit for the week",
    minutes: 20, feeds: "5 school days",
    storage: "Snack bins by the fridge, labelled M–F." },
];
